# Cloudflared tunnel for AppFlowy
services:
  cloudflared:
    restart: on-failure
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml
      - ./cloudflared/credentials.json:/etc/cloudflared/credentials.json
    networks:
      - appflowy-cloud_default

networks:
  appflowy-cloud_default:
    external: true
