tunnel: <your-tunnel-id>
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: appflowy.ramonma.online
    service: http://appflowy-cloud-caddy-1:80
  - service: http_status:404
